### ISSUE TITLE
Design des différents équipements

### ISSUE THREAD

**Issue by florianpanchout** [datagir/wattris#10]
Représenter visuellement [les différents équipements](https://github.com/datagir/simulateurpuissance/issues/11) (avec leurs différentes déclinaisons) sous forme d'agencement de blocs.

Cette liste a deux objectifs : 
- Vérifier la faisabilité de notre wireframe, selon la taille et la forme des équipements
- Permettre d'avoir un document pour faire valider par l'ADEME / RTE les formes des équipements

**Comment by florianpanchout** [comment]
[Une proposition](https://www.figma.com/file/cJYrwRiAvp1DJ6ZAbAkX1K/Wattris?node-id=53%3A2) de ce à quoi ça pourrait ressembler

**Comment by florianpanchout** [comment]
Équipement à traiter en priorité :
- Radiateurs
- Réfrigérateur simple (1 porte)
- Lave-linge
- Four électrique
- Box internet

**Comment by florianpanchout** [comment]
En faisant des tests rapides pour l'UI, je m'interroge sur la pertinence des formes de blocs complexes pour beaucoup d'équipements : Si notre visualisation est précise à l'heure et que j'utilise mes plaques de cuissons pendant 1h ou moins, on se fiche un peu de savoir ou est l'appel de puissance.

Je suis a peu prêt sur que le français moyen n'est pas notre grand mère qui faisait mijoter son repas pendant 6h (et [cette étude](https://librairie.ademe.fr/changement-climatique-et-energie/4473-panel-usages-electrodomestiques.html) me donne raison avec une durée d'utilisation moyenne d'un four de 51 minutes)

**Comment by Clemog** [comment]
Je partage, même avec une maille à 30 minutes
Par contre je pense que ça reste intéressant de montrer l'appel de puissance important au départ pour certains appareils

**Comment by martinregner** [comment]
Vu que l'enjeu c'est la pointe, est-ce qu'un écran zoom sur 18-20 où l'on pourrait passer à des pas de 30min (voire 15) ne serait pas nécessaire ?

**Comment by Clemog** [comment]
J'ai essaye de compléter le chauffage, chauffe eau (vraiment pas évidents) et l'ampoule ..
On en rediscute :)

**Comment by florianpanchout** [comment]
On peut fermer cette issue ou il y nous manque encore des trucs @clemog ?

**Comment by Clemog** [comment]
Pour moi on est bon sur la complétude des équipements, à voir si le design doit être revu, on pourra ouvrir une issue spécifique sur l'un des appareils
