### ISSUE TITLE
Intégrer des trackeurs sur Matomo

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#108]
Pour mieux suivre les comportements & parcours utilisateur mettre en place du tracking sur les boutons du simulateur et les suivre sur matomo

**Comment by Clem-mrtn** [comment]
Une première liste non exhaustive des boutons à tracker : 
- Bouton "Ajouter un appareil" 
- Tous les boutons appareils _(lave-linge, plaques, aspirateur, etc.)_
- Bouton "Ajouter un appareil' sur la popin (pour ajouter un 2ème appareil)
- Bouton **"?"** 
- Bouton "Découvrez comment faire des économies d'énergie" 
- Les cartes en bas du graphique 

Je me dis aussi que ça peut être intéressant de tracker : 
- les clics sur le grahique : est-ce que les utilisateurs cliquent intuitivement sur les formes directement sur le graphique ? (<=> drag & drop)
- Est-ce qu'on souhaite monitorer aussi les clics sur les slider temps ? Est-ce que c'est faisable ? 

N'hésitez pas à compléter la liste si vous en voyez d'autres mais je trouve que ça donne déjà des premières informations intéressantes

**Comment by florianpanchout** [comment]
Done : https://deploy-preview-126--wattris.netlify.app/
