### ISSUE TITLE
Définir la liste des équipements

### ISSUE THREAD

**Issue by florianpanchout** [datagir/wattris#11]
Définir la liste des équipements disponible à l'ajout, ainsi que leur déclinaisons possibles

Liste au 12/10 : 
- Radiateurs
- Chauffe-eau
- Réfrigérateur
- - simple (1 porte)
- - combiné (2 portes)
- Congélateur indépendant
- Lave-linge
- Sèche-linge
- Lave-vaisselle
- Aspirateur traineau
- Plaque de cuisson vitrocéramique
- Four électrique
- Four micro-ondes
- Bouilloire
- Téléviseur
- Box internet
- Décodeur TV
- Ordinateur
- - portable
- - fixe
- Charge smartphone
- Sèche-cheveux
- Luminaires

**Comment by florianpanchout** [comment]
Pour l'instant j'ai : 

- Réfrigérateur simple (1 porte)
- Radiateurs
- Réfrigérateur simple (1 porte)
- - simple (1 porte)
- - combiné (2 portes)
- Congélateur indépendant
- Lave-linge
- Sèche-linge
- Lave-vaisselle
- Aspirateur traineau
- Plaque de cuisson vitrocéramique
- Four électrique
- Bouilloire
- Téléviseur
- Box internet
- Décodeur TV
- Ordinateur

@Clemog @martinregner vous en voyez d'autres ?

**Comment by Clemog** [comment]
Micro-ondes ? On peut préciser aussi peut être Ordinateur "fixe" (je sais pas s'il y a une différence importante avec un ordi portable sur secteur (peut etre l'ecran)
Je vois aussi qu'il y a deux fois réfrigérateur simple

**Comment by martinregner** [comment]
Micro-onde est arrivé dans le nouveau fichier, je pense qu'il faut l'ajouter aussi.
Je garderai "Bouilloire" car il peut faire parti de la préparation du repas, mais je te rejoins il ne faut pas aller jusqu'au sèche-cheveux ni grille-pain.

A notre échelle, ça ne va peut-être pas changer grand chose ordinateur ou ordinateur portable si ? (il doit tout de même y avoir un facteur 2, mais vu l'échelle...). 

Je pense qu'il faudrait ajouter aussi smartphone en charge. Ce sera l'épaisseur du trait, mais histoire de justement montrer les ordre de grandeur. --> Env. 4W sur 2h

**Comment by florianpanchout** [comment]
Est-ce que le sèche cheveux ne mériterait pas d'être dans la liste ? C'est un gros appel de puissance très bref non ?

**Comment by Clemog** [comment]
On peut ajouter aussi fer à repasser peut être :)

**Comment by martinregner** [comment]
Très bien cette liste.
Dans la catégorie "épaisseur du trait", que pensez-vous d'ajouter "une ampoule" ? C'est pour la pédagogie éclairage (env. 15W) vs le reste. Ce sera difficile pour l'utilisateur qui a peut-être + qu'une ampoule dans la pièce de se projeter, mais il ne faut peut-être pas trop complexifier.
Eventuellement, on pourrait imaginer choisir plusieurs ampoule et plusieurs radiateurs.

**Comment by Clemog** [comment]
> Eventuellement, on pourrait imaginer choisir plusieurs ampoule et plusieurs radiateurs.

On peut faire ça oui, sachant que je suis parti dans le design d'une puissance installée pour le chauffage (donc plusieurs radiateurs), c'est peut etre critiquable !
