### ISSUE TITLE
🐛 Bug padding cartes appareils

### ISSUE THREAD

**Issue by Clemog** [datagir/wattris#110]
Suite au merge de #97, j'ai oublié de gérer le padding au moment des conflits de branches

**Comment by Clemog** [comment]
Done : https://deploy-preview-111--wattris.netlify.app/

**Comment by Clem-mrtn** [comment]
![Capture d’écran 2023-01-10 à 11 08 07](https://user-images.githubusercontent.com/76995768/211522416-0336594c-48d4-4247-a610-0f9c7e3b2b95.png)

On est au max ? Parce que ça sort encore un tout petit peu quand on joue avec les horaires de fin de journée

**Comment by Clemog** [comment]
On est au max pour quel élément ?

**Comment by Clem-mrtn** [comment]
Corrigée par les fix de la #112
