### ISSUE TITLE
🐛 Slider temps inutilisable sur mobile

### ISSUE THREAD

**Issue by Clemog** [datagir/wattris#112]
Bug du "StartAndEndSelector" qui rend le simulateur bcp moins pertinent sur mobile 😅

<img width="386" alt="image" src="https://user-images.githubusercontent.com/55186402/211493503-20d8a655-383e-4db2-b08b-0b857c78d632.png">

Il y a aussi un bug au niveau de la fusion du label : si les thumbs se surperposent d'emblée, la fusion des labels ne se fait pas 😢

**Comment by Clemog** [comment]
Done : https://deploy-preview-113--wattris.netlify.app/

**Comment by Clemog** [comment]
> Il y a aussi un bug au niveau de la fusion du label : si les thumbs se surperposent d'emblée, la fusion des labels ne se fait pas 😢

Je ne l'ai pas toujours, j'ai l'impression que c'est surtout sur mobile. Est ce qu'on ne devrait pas désactiver la possibilité d'overlap (de passer par dessus l'autre thumb) sur mobile ? Je trouve que ça rend l'utilisation super difficile .. Vous en pensez quoi @Clem-mrtn @florianpanchout ?

**Comment by Clem-mrtn** [comment]
Sur ordi je n'ai pas de problème 
Sur mobile, je n'ai effectivement plus le bug, par contre j'ai un petit bug d'affichage : 
![IMG_E76D7159A38A-1](https://user-images.githubusercontent.com/76995768/211523246-16af46a0-cbeb-4ef5-9937-d0a4553f3ede.jpeg)

Sinon dans l'usage sur mobile, je trouve que ça va on arrive à overlaper sans trop trop de contraintes

**Comment by Clemog** [comment]
Ah oui étrange, je ne vois pas d'où ça peut venir

**Comment by Clem-mrtn** [comment]
Correction 1 : Afficher uniquement l'heure de départ sur les cartes du bas, en dessous du graphique 
Correction 2 : bug de focus ?

**Comment by Clemog** [comment]
Je me rends compte qu'il y a aussi un bug avec le slider qui ouvre automatiquement la fenêtre de modif au clique, j'essaie de corriger ce bug aussi ici

**Comment by Clemog** [comment]
La barre n'est plus cliquable ! En revanche, je ne comprends vraiment pas le bug sur mobile ..
Je pense qu'on peut merger la PR et ouvrir une autre issue pour ce bug ?

**Comment by Clemog** [comment]
> Il y a aussi un bug au niveau de la fusion du label : si les thumbs se surperposent d'emblée, la fusion des labels ne se fait pas 😢

Il y a bien ce problème pour la télévision par exemple : je crois que c'est un pb avec le hook `useThumbOverlap` @florianpanchout qui n'est pas lancé au premier render

**Comment by florianpanchout** [comment]
>  je crois que c'est un pb avec le hook useThumbOverlap @florianpanchout qui n'est pas lancé au premier render

Apparemment. J'ai tenté [un fix](https://github.com/datagir/wattris/pull/113/commits/51d800f8f93267b993eff5e885fc5d7d724b2e43)

On perds toujours le focus sur mobile (en touch en général j'imagine) lorsque les thumbs changent d'état. S'il n'est pas possible de corriger ça je me demande s'il ne vaut pas mieux forcer l'affichage avec les heures en haut sur mobile

**Comment by Clemog** [comment]
> On perds toujours le focus sur mobile (en touch en général j'imagine) lorsque les thumbs changent d'état. S'il n'est pas possible de corriger ça je me demande s'il ne vaut pas mieux forcer l'affichage avec les heures en haut sur mobile

Effectivement j'avais remarqué ce bug, il semble que ça le fait seulement avec l'un des thumbs

**Comment by florianpanchout** [comment]
J'ai le problème avec les deux

**Comment by Clem-mrtn** [comment]
J'ai tenté de vous faire une petite capture d'écran de mon test sur mobile : quand les deux sliders sont rapprochés en heure sur mobile ça "bug", on galère à reprendre la main pour les déplacer (ça le fait surtout sur les horaires max, en bout de timeline)
C'est peut-être pas un bug mais juste l'usage sur Mobile qui n'est vraiment adapté ? 
https://user-images.githubusercontent.com/76995768/212025482-0b729500-2406-48a0-8e5e-ebff1883cf61.MOV

**Comment by Clemog** [comment]
> On perds toujours le focus sur mobile (en touch en général j'imagine) lorsque les thumbs changent d'état. S'il n'est pas possible de corriger ça je me demande s'il ne vaut pas mieux forcer l'affichage avec les heures en haut sur mobile

Je pense que c'est lié à ça @Clem-mrtn, est ce qu'on partirait pas sur la solution évoquée par @florianpanchout ?

**Comment by Clemog** [comment]
Je pense qu'on peut merger dans un premier temps cette PR et je peux regarder pour trouver une solution sur mobile (ce sera toujours mieux que l'actuel)

**Comment by Clem-mrtn** [comment]
Ok 
Good pour merger et je créé une autre issue sur le sujet 👍
