### ISSUE TITLE
Clarifier l'affichage des horaires lorsque l'usage s'étale sur 2 jours 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#118]
Quand j'ajoute l'appareil télévision, que je veux caler par exemple mon **usage de 20h30 à 23h30 et** que je joue avec les sliders, la carte s'affiche et reste en rouge alors que je suis en période hors tension 

![Capture d’écran 2023-01-12 à 14 48 19](https://user-images.githubusercontent.com/76995768/212086219-991b451d-0c03-4eca-9f95-abe612e61ca7.png)
![Capture d’écran 2023-01-12 à 15 00 53](https://user-images.githubusercontent.com/76995768/212086567-a4c00abb-5d2b-4bb6-a650-d17fc9a5d95d.png)

**Comment by florianpanchout** [comment]
Ta télé est allumée de 22h30 à 22h sur ton premier screen (et 8h à 4h30 sur le deuxième).

Une solution serait d'inverser l'ordre des heures dans le thumbs. On pourrait aussi afficher la phrase complète "de 22h30 à 22h" (comme lorsque les thumbs sont détachés)

**Comment by florianpanchout** [comment]
Effectivement. J'ai juste inversé les heures (pour toujours afficher l'heure de début en premier).
C'est visible ici : https://deploy-preview-127--wattris.netlify.app/
