### ISSUE TITLE
Enlever une virgule dans le sous-texte d'introduction 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#120]
Retour Florence : 
>  il faut enlever la virgule après **découvrez quels appareils consomment beaucoup** sur le deuxième écran de Wattris.
![image](https://user-images.githubusercontent.com/76995768/212122377-75387361-f1cc-4580-85c6-03a207b1e78d.png)

**Comment by Clemog** [comment]
Je prends

**Comment by Clemog** [comment]
C'est bon !
