### ISSUE TITLE
Sélectionner une durée d'utilisation des petits appareils >5min

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#122]
Il y a un bug quand on essaye de changer la durée d'utilisation du micro-onde, d'une bouilloire ou du sèche cheveux pour mettre plus que 5 min 
![Capture d’écran 2023-01-16 à 11 08 20](https://user-images.githubusercontent.com/76995768/212652534-263f799f-1f27-4958-b10c-cc34b649a54a.png)

**Comment by Clemog** [comment]
C'est corrigé ici : https://deploy-preview-125--wattris.netlify.app/
