### ISSUE TITLE
Modifier les hypothèse d'usages des appareils et leur forme 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#123]
On a eu un retour métier de Thérèse du service bâtiment, suite aux hypothèses prises pour les appels de puissance des différents appareils 
Je vous les partage : 

> - Radiateur électrique :
Le choix de n'inclure qu'un seul appel de puissance au départ puis plus rien sur le reste de la période (quelque soit la durée) ne paraît pas réaliste. Le déclenchement du radiateur se fait plusieurs fois par jour, surtout en période de froid. C'est vrai que le moment où les appels de puissance se produisent dépend de beaucoup de facteurs (météo, isolation, taille de la pièce, etc.) mais ça ne semble pas la meilleure solution de ne rien représenter car ça minore largement le rôle du chauffage électrique.
Les données de PANEL ELECDOM montrent qu'en moyenne les logements chauffés avec des convecteurs électriques consomment 3156 kWh/an pour le chauffage pour une puissance installée de 5323 W. Cela représente 593 h de fonctionnement des appareils sur l'année. En considérant que l'essentiel du chauffage est réalisé pendant la saison de chauffe (6 mois), cela revient à 593 h de fonctionnement sur une période de 4320 h, soit environ 14% du temps de fonctionnement effectif des convecteurs. Ce serait donc préférable lorsqu'on ajoute un radiateur électrique dans Wattris, que la durée pendant laquelle l'appareil appelle de la puissance représente 14% de la période considérée répartie en plusieurs appels. Par exemple si un radiateur électrique est lancé de 8h à 22h, il doit être en fonctionnement pendant 14% de 14h soit 2 heures, qui peuvent être répartis en 4 appels de 30 minutes toutes les 3,5h. Pour un appareil utilisé 24h/24, la durée de fonctionnement doit être 3,4h sur la période, qui peuvent se répartir en 7 appels de 30 minutes se produisant toutes les 3,5h. Et ainsi de suite.
Si l'idée est de modéliser la puissance pendant les périodes en tension, c'est à dire de grand froid, alors on ne doit pas prendre la moyenne sur la saison de chauffe mais par exemple doubler les valeurs précédentes car les jours de grand froid les appels de puissance sont bien plus nombreux. Cela représente alors une durée de 30% de fonctionnement, qui peut se répartir par exemple en 30 minutes de fonctionnement toutes les 1,75h.
Enfin, il n'est pas très clair pourquoi hors périodes de fonctionnement Wattris attribue un appel de puissance continu de 100 W aux radiateurs électriques. Certes quand un convecteur n'est pas en train de chauffer il continue à avoir une consommation (pour le thermostat, etc.) mais elle est très inférieure à 100 W.

> - Four électrique :
Ce n'est pas vraiment réaliste de ne considérer que l'appel de puissance initial (pour préchauffer le four) et ensuite plus rien. Car en réalité il y a ensuite une succession assez rapprochée de nombreux appels brefs de puissance pour maintenir la température, comme on peut le voir sur un exemple de four mesuré à la minute près dans l'étude ADEME sur la cuisson de 2018 (page 71).
On voit la multitudes d'appels après la période initiale de chauffe. Il serait plus réaliste de modéliser une succession de pics brefs (par exemple 5 minutes toutes les 5 minutes) sur l'ensemble de la durée de la cuisson après le préchauffage.

![image](https://user-images.githubusercontent.com/76995768/212654178-3bbfff5b-04de-4f93-9346-9f63cdf73aa7.png)

> - Lave-vaisselle :

La répartition des appels de puissance est incorrecte. Dans un cycle de lave-vaisselle il y a effectivement un premier appel de puissance au début pour chauffer l'eau (par exemple 15 minutes à 2000 W), puis une longue période inférieure à 100 W mais il y a aussi un appel fort de puissance à la fin du cycle pour sécher la vaisselle (à nouveau 15 minutes à 2000 W). Il conviendrait que Wattris représente les deux appels du début et de la fin du cycle et non un seul.

> - Sèche-linge :

L'hypothèse prise d'un fonctionnement en continu à puissance maximale n'est pas forcément très réaliste, notamment pour les modèles récents, mais ça peut aller en première approximation.

> - Plaques électriques :

L'hypothèse que la puissance appelée par une plaque de cuisson est continue et maximale pendant toute la cuisson n'est pas vraiment crédible. Après une période de chauffe initiale, la plaque fonctionne par intermittence (cf. remarque similaire que pour les fours électriques).

> - Bouilloire :
Le bouton pourrait s'appeler "bouilloire ou machine à café" car les cafetières sont très répandues dans les logements.

> - Sèche-cheveux :
On dispose de très peu de données et de mesures sur cet appareil, il est très difficile de savoir s'il fonctionne effectivement en permanence à pleine puissance à 2000 W en moyenne. C'est donc une hypothèse théorique.

> - TV :
La valeur de 120 W paraît trop élevée. La majorité des écrans LED sont inférieurs à 100 W. Il n'y a que les plasmas qui consomment beaucoup plus mais il n'y en a pratiquement plus dans les logements. Une valeur de 80 W semblerait plus réaliste.

>- Fer à repasser :
Un fer chauffe par intermittence, avec une succession de cycles on et off de quelques minutes (à peu près de même durée). Il n'est donc pas correct de le modéliser comme une puissance en continu à 2000 W. Si on veut simplifier quand même, il faut le considérer comme une puissance continue mais valant la moitié (1000 W).

> - Chauffe-eau :
Une des hypothèses semble incorrecte. Un ballon d'eau chaude a besoin de puissance électrique bien plus longtemps que 10 minutes pour chauffer son eau.
Le rapport PANEL ELECDOM trouve une consommation moyenne de 1676 kWh/an pour une puissance moyenne de 2250 W pour les ballons électriques. Cela signifie qu'un ballon moyen chauffe pendant 745h sur une année, soit environ 2h par nuit. Il faut donc remplacer dans Wattris la durée de 10 minutes par 2 heures. Ensuite, dans la journée le ballon n'appelle plus de puissance (on peut donc retirer les 20 W).
Par ailleurs ce serait utile de remplacer le nom du bouton par "Ballon d'eau chaude" plutôt que "chauffe-eau" sans précision.

> - Ampoule LED :
PANEL ELECDOM montre que la puissance moyenne des ampoules LED installées dans les logements est plutôt 7 W que 10 W. Mais il reste encore un nombre significatif d'ampoules qui ne sont pas des LED et qui consomment beaucoup plus. Ce serait probablement utile de rajouter un bouton "ampoule à filament non LED" pour montrer la différence. Toujours selon PANEL, la puissance moyenne des anciennes ampoules (non-LED et non-LFC) encore installées dans les logements est 45 W.

> - Appareils de froid :
L'hypothèse de les modéliser par un appel de puissance continu n'est malheureusement pas très conforme à la réalité. Ces appareils fonctionnent par cycles de compression qui se produisent tous les 1/5ème du temps environ (pour simplifier). Ce serait mieux, si possible, de les modéliser par des périodes à pleine puissance pendant (par exemple) 25 minutes suivies par des temps sans puissance pendant 100 minutes. Mais c'est bien sûr impossible de savoir exactement quand chaque cycle démarre dans un logement donné.

> - Autres appareils :
Ce serait utile de prendre en compte la puissance appelée par les appareils en veille. Cela pourrait être fait par le biais d'un nouveau bouton appelé "veilles"  où l'utilisateur indiquerait le nombre d'appareils en veille dans son logement (avec une puissance de 1,5 W attribuée à chaque veille). Ou en ajoutant directement d'entrée de jeu une base de veilles sur le graphique. PANEL ELECDOM estime la puissance moyenne des appareils en veille à 45 W par logement.

**Comment by Clem-mrtn** [comment]
Je vous partage ici ses retours bruts.
On est clairement sur une meta issue qui mérite d'être découpée, mais je propose de s'en parler pour voir s'il y a des optimisations sur lesquelles on est d'accord et qu'on pourrait mettre à jour "facilement" et statuer sur celles qui semblent être trop "**métiers**" et complexes à simplifier visuellement.

**Comment by florianpanchout** [comment]
Trop cool ces retours ! Mais ou était cette dame quand on avait besoin d'elle ?

**Comment by Clemog** [comment]
Thérèse est la personne qui nous avait demandé "nos sources", c'est aussi la personne qui est à l'origine de l'excel sur la majorité des caractéristiques des appareils, effectivement, c'est très intéressant !

**Comment by Clem-mrtn** [comment]
En complément, retour du RTE : 
> Il y a des choses à améliorer, qui peuvent décrédibiliser les chiffres. La modélisation du chauffage en particulier est étonnante, puisqu’elle suppose un démarrage et période de chauffe à fond, comme pour le démarrage d’un four par exemple. Il vaudrait mieux avec un type de programmation ans la journée, pour avoir une expérience réaliste. Et idéalement une configuration des équipements du foyer : taille des pièces, puissance de chauffe, congélateur ou non etc, un mode de consommation initial et voir ensuite coment décamler 

- Pour la partie chauffage s'est beaucoup remonté par les experts ADEME / RTE à voir comment on peut simplement le modéliser pour être + en accord avec la réalité et crédible 
- Four je maintiens que pour un petit usage on compléxifie la lecture du graphique 
- Partie configuration du foyer on est hors scope v1
