### ISSUE TITLE
Afficher un pic de consommation à la fin de l'usage du lave-vaisselle  

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#128]
Suite au retour de Thérèse et dans le cas du lave-vaisselle :
>  La répartition des appels de puissance est incorrecte. Dans un cycle de lave-vaisselle il y a effectivement un premier appel de puissance au début pour chauffer l'eau (par exemple 15 minutes à 2000 W), puis une longue période inférieure à 100 W mais il y a aussi un appel fort de puissance à la fin du cycle pour sécher la vaisselle (à nouveau 15 minutes à 2000 W). Il conviendrait que **Wattris représente les deux appels du début et de la fin du cycle et non un seul.**

Ajouter donc un pic de consommation à la fin de l'usage de l'appareil (<=> ajouter une heure de fin à l'usage)

**Comment by florianpanchout** [comment]
Visible ici : https://deploy-preview-142--wattris.netlify.app/

C'est mignon ce petit U je trouve
