### ISSUE TITLE
Ajouter un bouton "Mes appareils en veille" 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#134]
Suite au retour de Thérèse : 
> Ce serait utile de prendre en compte la puissance appelée par les appareils en veille. Cela pourrait être fait par le biais d'un nouveau bouton appelé "veilles"  où l'utilisateur indiquerait le nombre d'appareils en veille dans son logement (avec une puissance de 1,5 W attribuée à chaque veille). Ou en ajoutant directement d'entrée de jeu une base de veilles sur le graphique. PANEL ELECDOM estime la puissance moyenne des appareils en veille à 45 W par logement.

- Ajouter à la liste un bouton "appareils en veille" et afficher dans la carte appareil qu'on en a en moyenne une 30aine chez nous et que la totalité de ces appareils consomment **45W** 
- Afficher ces appareils en veille sur le graphique

**Comment by Clem-mrtn** [comment]
@Clemog 
Une petite reformulation de l'hypothèse : 
" Cela correspond à tous vos appareils en veille, vos appareils branchés. En moyenne, nous estimons la puissance moyenne des appareils en veille à 45 W par logement."

En relisant le texte de Thérèse, je me dis que c'est une valeur plus arbitraire de parler des 30 appareils dans le foyer que de simplement parler de la moyenne / logement.

**Comment by Clemog** [comment]
Ça marche, j'ai reformulé la fin quand même (je trouve que c'est mieux de rester factuel et de pas avoir le "nous" :)

    "description": "Cela correspond à tous vos appareils en veille, vos appareils branchés. En moyenne, la puissance moyenne des appareils en veille est de 45 Watt par logement."
