### ISSUE TITLE
Modélisation du chauffage 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#135]
Suite au retour de Thérèse et aux échanges avec Céline, tester une première nouvelle conception de la forme chauffage en jour de froid :
- Conserver la forme "L" avec un **pic de conso à l'allumage à 2000W** puis un pallier à **1000W** pour le reste de la consommation de la journée 
- Mettre à l'échelle le graphique lors de l'ajout d'un radiateur électrique 
- Mettre à jour les hypothèses, en spécifiant qu'on parle d'un _jour de froid_ et en expliquant peut-être qu'en fonction des températures extérieurs et de la température consigne la puissance émanant du radiateur varie. 

/!/ Surveiller le score consommation dont il faudra sans doute retravailler l’échelle pour ne pas exploser son score si l'on ajoute un ou plusieurs radiateurs 
et + attention au message que l'on envoie sur le chauffage à l’électricité (vs. chauffage au fioul ou au gaz)

**Comment by florianpanchout** [comment]
L'affichage avec 1000W constant (et une mise à l'échelle du graph) est visible ici : https://deploy-preview-140--wattris.netlify.app/

Ça rends l'ensemble très brouillon je trouve

**Comment by Clem-mrtn** [comment]
Validé par les métiers suite à la PR #141 
Je ferme donc cette issue et on peut fermer la PR #140
