### ISSUE TITLE
Modifier le texte des scores consommation

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#136]
Nouveau retour de Florence suite aux remarques de RTE : modifier le texte du score et **ne + afficher le la conso en kWh** qui ne sera pas compris pas l'utilisateur 

- Score 1 (faible) : **"Consommation faible pendant les périodes de tension. 
Votre consommation ne met pas le réseau électrique en tension."**

- Score 2 (modéré) : **"Consommation importante pendant les périodes de tension. 
Votre consommation risque de mettre le réseau électrique en tension. Essayer de décaler le fonctionnement de certains appareils en dehors des périodes de tension."**

- Score 3 (fort) : **"Consommation très importante pendant les périodes de tension.
Votre consommation met très fortement le réseau électrique en tension et des coupures sont possibles. Essayer de décaler le fonctionnement de vos appareils en dehors des périodes de tension."**

**Comment by florianpanchout** [comment]
Il y a une seule phrase sur les 8 qui ne termine pas par "tension"...

Je me suis permis de raccourcir un peu. C'est visible ici : https://deploy-preview-139--wattris.netlify.app
