### ISSUE TITLE
Tester une nouvelle UI pour ajouter des appareils

### ISSUE THREAD

**Issue by florianpanchout** [datagir/wattris#16]
Un retour de Livio : 
La liste des appareils n'est pas très longue et plutôt "standard". Il serait peut être plus efficace de l'afficher directement sur la gauche de l'écran avec la possibilité de changer l'horaire directement. Cela permettrait aussi d'afficher un foyer "par défaut".

**Comment by Clemog** [comment]
Yes, je partage, ça va dans le sens d'un des commentaires sur le figma il me semble :)

**Comment by Clem-mrtn** [comment]
Après quelques tests & échanges sur le sujet, on peut trouver un entre-deux : 
- Afficher seulement quelques appareils (2 ou 3) d'un foyer moyen 
- Intégrer un petit tuto dynamique & simple pour faciliter la compréhension de l'interface 
- Pousser l'utilisateur à passer à l'action en ajoutant d'autres appareils de son foyer pour le lancer dans sa simulation 
- A l'ajout d'appareil, tester de regrouper ceux affichés en rouges et ceux en bleus

**Comment by florianpanchout** [comment]
[Nouvelle version visible ici](https://newappliances--wattris.netlify.app/)

![Image](https://user-images.githubusercontent.com/8115933/204732704-498ab1e3-2ad3-4317-9ad1-7332b564831b.png)

**Comment by Clem-mrtn** [comment]
J'imagine que tu dois modifier des trucs en parallèle mais quelques remarques sur cette version : 

- Sur mon écran , quand je clique sur *"Ajouter un appareil"*, la pop-in s'affiche au dessus, dans le graphique et je ne la vois pas. Je suis obligée de scroller pour la voir
-  Dans la pop-in pour choisir son appareil, je mettrais plutôt un select, qu'un "slider" puisque c'est une liste déroulante qui s'affiche 
- Pourquoi est-ce que j'ai un highlight sur le graphique quand je passe la souris sur les *plaques électriques* et pas quand je passe sur le lave linge ?
- Je rajouterais une petite croix sur la pop-in pour pouvoir instinctivement fermer la fenêtre plutôt que de *supprimer*
- Je ne comprends pas trop l'affichage du radiateur sur une longue durée 
![image](https://user-images.githubusercontent.com/76995768/204781818-b559c5cc-8263-445c-b2f0-d47e1330017a.png)

Sinon je trouve ça bien de pouvoir jouer aussi avec le *slider temps* pour positionner l'appareil sur le graphique 😃

**Comment by florianpanchout** [comment]
> Dans la pop-in pour choisir son appareil, je mettrais plutôt un select, qu'un "slider" puisque c'est une liste déroulante qui s'affiche

J'ai peur que les gens passent à côté de l'affichage en select, même si c'est effectivement plus cohérent

Je suis en train de corriger le reste

**Comment by Clemog** [comment]
Je partage les retours (j'allais en écrire certains et en fait pas besoin ;) )

Pour itérer sur la pop in d'ajout et le fait qu'au contraire pour moi, le slider est peu intuitif, je propose une autre idée : 
<img width="733" alt="image" src="https://user-images.githubusercontent.com/55186402/205017465-207bde05-4b31-4e66-a9eb-0f143cba25ea.png">

**Comment by Clem-mrtn** [comment]
> je propose une autre idée :

Je trouve ça très bien aussi 👍 
Mais tu as toujours cette idée de positionner l'appareil sur le graphique avec le slider ? (ce que tu ne trouvais pas intuitif?)

> J'ai peur que les gens passent à côté de l'affichage en select, même si c'est effectivement plus cohérent

Pourquoi il passerait à côté du select si on affiche une petit flèche vers la liste déroulante par ex ? 
Pour moi si on veut garder le slider plutôt que d'avoir une liste déroulante, il faut l'assumer jusqu'au bout et qu'il y ait un vrai effet de slide entre un appareil & un autre (comme sur nos pages équivalent ou infographies sur impact CO2)

**Comment by florianpanchout** [comment]
Nouvelle version en ligne basé sur le wireframe de Clément : 

![Image](https://user-images.githubusercontent.com/8115933/205318733-9a2b4a8b-6b92-4154-b8b4-80caf7e1140b.png)

**Comment by Clemog** [comment]
top ! Je mettrais pas un `select` pour le durée, je trouve qu'un "+" ou "-" serait plus parlant (à part peut etre pour le radiateur)

**Comment by Clem-mrtn** [comment]
#37
