### ISSUE TITLE
Affichage d'incréments plus précis sur la frise

### ISSUE THREAD

**Issue by florianpanchout** [datagir/wattris#17]
Il est nécessaire de passer à des incréments de 30 minutes, (a minima pendant les pics). Deux propositions dans ce sens : 

- [Version 1](https://www.figma.com/proto/cJYrwRiAvp1DJ6ZAbAkX1K/Wattris?page-id=63%3A23&node-id=157%3A67&viewport=-2734%2C700%2C1&scaling=scale-down)
- [Version 2](https://www.figma.com/proto/cJYrwRiAvp1DJ6ZAbAkX1K/Wattris?page-id=63%3A23&node-id=413%3A5&viewport=-2734%2C700%2C1&scaling=scale-down)

**Comment by martinregner** [comment]
Avec 3 usages, on ne teste peut-être pas complètement la lisibilité de l'une ou l'autre.

Les petits carreaux de la version 2 semblent plus "logiques" si on veut garder des blocs qui couvrent forcément le pas de temps, et éviter des demi carrés au sein d'une case horaire (sinon, pourquoi faire des carrés finalement...).
.. mais c'est plus chargée et moins lisible (ex le C en très petit).

Il va y avoir d'autres retours de la part du petit groupe de travail

**Comment by florianpanchout** [comment]
J'ai essayé d'inclure la majorité des gros appareils ([Version 1](https://www.figma.com/proto/cJYrwRiAvp1DJ6ZAbAkX1K/Wattris?page-id=63%3A23&node-id=157%3A67&viewport=-2734%2C700%2C1&scaling=scale-down), [Version 2](https://www.figma.com/proto/cJYrwRiAvp1DJ6ZAbAkX1K/Wattris?page-id=63%3A23&node-id=413%3A5&viewport=-2734%2C700%2C1&scaling=scale-down)). 

Je trouve la version 2 beaucoup trop chargée.

**Comment by florianpanchout** [comment]
Traité via #23
