### ISSUE TITLE
Tester une nouvelle UI pour l'affichage des "petits" appareils

### ISSUE THREAD

**Issue by florianpanchout** [datagir/wattris#19]
L'affichage des petits appareils (box, ampoule, etc...) n'est pas satisfaisant pour l'instant. Peut être tous les regrouper via #16 ?

**Comment by florianpanchout** [comment]
La plupart des appareils peuvent rentrer dans cette catégorie en fait : 

Si on additionne toute la première ligne sauf TV (Réfrigérateur + réfrigérateur combiné + congélateur + box internet + box TV + smartphone + laptop + ordinateur fixe) on arrive à 216W...

Tous ces appareils n'apportent rien à notre message ([le focus sur les pics de consommation](https://github.com/datagir/wattris/issues/5#issuecomment-1268609832)) : est ce qu'il ne faudrait pas tous les regrouper dans une catégorie affichée par défaut (et impossible à enlever) qui prendrait 200W (ce qui semble déjà très généreux) en bas ? On expliquerait simplement au clic ce que cette catégorie contient

**Comment by florianpanchout** [comment]
Retour de @Clem-mrtn : 
> Réfléchir comment bien afficher les appareils qui consomment de manière constante de l'électricité (la box internet, le frigo etc.) pour éviter que l'utilisateur pense qu'ils consomment très peu vs. d'autres appareils éléctro-ménager

**Comment by Clem-mrtn** [comment]
#32
