### ISSUE TITLE
Ajouter une légende au graphique 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#20]
Ajouter une légende sous le graphique pour savoir : 
- à quoi équivaut 1 carré par exemple
- les zones rouges, période de surtension 

Est-ce qu'on rajoute également des légendes sur les axes ? _(Temps, Watt..)_

**Comment by florianpanchout** [comment]
Issue traitée par https://github.com/datagir/wattris/issues/31 et https://github.com/datagir/wattris/issues/27
