### ISSUE TITLE
Affichage de la Box internet, frigo (conso constante)

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#21]
Réfléchir comment bien afficher les appareils qui consomment de manière constante de l'électricité _(la box internet, le frigo etc.)_ pour éviter que l'utilisateur pense qu'ils **consomment très peu vs. d'autres appareils éléctro-ménager**

**Comment by florianpanchout** [comment]
Je pense que cette issue peut être traitée dans https://github.com/datagir/wattris/issues/19 pour simplifier les échanges
