### ISSUE TITLE
Clarifier le message : mieux consommer ou moins consommer 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#22]
> A première lecture, je pensais que le but du graphique était de montrer quel était ma consommation et mon score consommation dans une journée pour que j'optimise ma consommation. Je comprends finalement que c'est surtout comment mieux la répartir dans une journée

Attention au message que l'on souhaite faire passer en priorité. 
Si pour une v1 on veut vraiment que l'usager se concentre sur **les pics de consommation** et l'aider à déplacer ses usages il faut davantage concentrer nos efforts visuels là-dessus, plutôt que de lui faire passer un message sur son score consommation & des gestes de sobriété.

**Comment by florianpanchout** [comment]
Suite sur #23
