### ISSUE TITLE
Conception

### ISSUE THREAD

**Issue by florianpanchout** [datagir/wattris#23]
Regroupement de l'ensemble du travail et des échanges suite à [l'établissement du périmètre](https://github.com/datagir/wattris/issues/5) et [la rédaction des users stories](https://github.com/datagir/wattris/issues/7). 

Ce travail prends comme source [le design d'un wireframe](https://github.com/datagir/wattris/issues/2), et [d'une maquette](https://github.com/datagir/wattris/issues/12) tous deux validés par ADEME / RTE.

**Comment by florianpanchout** [comment]
2 prototypes sont visibles actuellement : 

### https://wattris.netlify.app/ 
#### Positif : 
- Ressemble beaucoup au wireframe / maquette déjà validés
- Permet de voir simplement quel appareil pose problème
- Permet de voir la forme qu'à un appareil
#### Négatif : 
- Visuellement très complexe (encore plus que la maquette qui avait des pas de 1h)
- Difficile de mettre en avant les pics de consommation avec autant d'information visuelle à l'écran
- Compliqué de trouver une façon d'identifier simplement les blocs sans surcharger l'affichage.
- L'information de la forme des blocs de chaque appareil rajoute une information peu claire et qui n'est pas dans le périmètre du simulateur

### https://blob--wattris.netlify.app/
#### Positif : 
- Visuel beaucoup plus simple. Rouge = mal. Mois de rouge = bien. Et c'est à peu près tout
- Les pics de consommation sont beaucoup plus mis en avant
#### Négatif : 
- Difficile d'identifier simplement quel appareil pose problème en ne regardant que le graph
- La forme des blocs est très peu mise en avant (mais ce n'est toujours pas un objectif du simulateur
- On s'éloigne beaucoup de l'idée originale

**Comment by florianpanchout** [comment]
[Issue](https://github.com/datagir/wattris/issues/22) de @Clem-mrtn dont la discussion peut continuer ici : 

>> A première lecture, je pensais que le but du graphique était de montrer quel était ma consommation et mon score consommation dans une journée pour que j'optimise ma consommation. Je comprends finalement que c'est surtout comment mieux la répartir dans une journée
>
>Attention au message que l'on souhaite faire passer en priorité.
Si pour une v1 on veut vraiment que l'usager se concentre sur les pics de consommation et l'aider à déplacer ses usages il faut davantage concentrer nos efforts visuels là-dessus, plutôt que de lui faire passer un message sur son score consommation & des gestes de sobriété.

**Comment by Clem-mrtn** [comment]
La 2ème version est forcément moins chargée que la 1ère, ça simplifie la lecture mais on identifie moins les appareils qu'on ajoute
Je me suis concentrée sur la 2ème version, mais plusieurs de mes remarques marchent pour les 2 affichages 

Au début je n'ai pas compris le choix des 2 couleurs : pq certains appareils étaient bleus ou rouge. Je comprends maintenant qu'ils changent de couleur en fonction des périodes de tension.
Je trouve que les jeux de surlignage sont bien
On a plus que des formes et plus de carrés : comment a-t-on l'échelle ?
Je n'afficherais pas toute la liste des appareils : j'afficherais 3/4 appareils puis je mettrais un bouton Ajouter d'autres appareils
Plus on rajoute des appareils, + le graphique prend de la place en hauteur sur la page, ce qui rend difficile la navigation, il faut scroller (surtout pour des petits écrans :hear_no_evil: )
Cela me fait aussi dire que sur la frise temps on a souvent un vide de 00h00 à 6h00, là où tout se concentre entre 7h & 22h : même si j'entends toutes les exceptions (faire tourner des machines la nuit en maison, les travailleurs de nuit...) : ça vaudrait le coup de pouvoir jouer avec des zooms ?
Ce n'est pas simple pour l'utilisateur de calculer le temps d'usage d'un appareil "j'utilise X pendant..". Est-ce que ce n'est pas + simple pour l'utilisateur de réfléchir en terme de créneaux ?
=> "Je cuisine de 19h à 20h"

Je me pose aussi la question pour les "petits appareils" que l'on utilise même pas pour des périodes de 30 minutes : ex le micro-onde, la bouilloire, le sèche cheveux (sauf pour les brushing :woman-tipping-hand: ) ?

**Comment by florianpanchout** [comment]
> On a plus que des formes et plus de carrés : comment a-t-on l'échelle ?

Est ce qu'on a besoin d'une échelle précise ? Je pense qu'on est d'accord pour dire qu'il faut que l'axe Y soit gradué (au moins le 0 et le 100%), mais a t'on besoin de plus ? Vu que l'on travaille avec un gros niveau d'imprécision, je trouve que ce n'est pas forcement une mauvaise chose de ne plus avoir les carrés

> Plus on rajoute des appareils, + le graphique prend de la place en hauteur sur la page, ce qui rend difficile la navigation, il faut scroller (surtout pour des petits écrans 🙉 )

Yes, pour l'instant c'est inutilisable. [On c'était dit qu'on mettait une hauteur fixe](https://github.com/datagir/wattris/issues/2#issuecomment-1273517421). Reste à trouver ensuite comment afficher les carrés qui dépassent

> Cela me fait aussi dire que sur la frise temps on a souvent un vide de 00h00 à 6h00, là où tout se concentre entre 7h & 22h : même si j'entends toutes les exceptions (faire tourner des machines la nuit en maison, les travailleurs de nuit...) : ça vaudrait le coup de pouvoir jouer avec des zooms ?

Le problème c'est qu'en faisant ça on risque de "cacher" un peu la solution. Mettre ces espaces vides en évidence c'est pour moi une façon de montrer "Hey regarde, c'est la qu'il faut que tu programmes ta machine (et déso pour tes voisins)"

> Ce n'est pas simple pour l'utilisateur de calculer le temps d'usage d'un appareil "j'utilise X pendant..". Est-ce que ce n'est pas + simple pour l'utilisateur de réfléchir en terme de créneaux ?

Ah c'est marrant je suis arrivé à ce design par deux reflexions : une totalement opposée ou je me suis dit que je savais combien de temps durait ma machine, ou combien de temps je passais l'aspirateur. Et une plus UI ou je me dis que le temps d'usage est généralement fixe (les gens vont pas utiliser leur four 30 minutes de moins parce qu'on leur dit), et que c'est avec l'heure de départ que l'on a envie de jouer
