### ISSUE TITLE
Ajouter un tutoriel in situ

### ISSUE THREAD

**Issue by florianpanchout** [datagir/wattris#25]
Au lancement du jeu, afficher un tutoriel interactif présentant les différents éléments de l'interface

**Comment by Clem-mrtn** [comment]
- [ ] conception du tuto @Clemog 
- [ ] dev du tuto en fonction des story board @florianpanchout

**Comment by florianpanchout** [comment]
Je propose comme première étape de mettre juste la première modal ("il fait froid dehors blablabla..."). Le temps de dev est très faible et ça nous permettrait d'avoir un simulateur autoportant en attendant des retours

**Comment by florianpanchout** [comment]
C'est visible ici : https://deploy-preview-65--wattris.netlify.app/
