### ISSUE TITLE
Identifier clairement les périodes de tensions

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#31]
> En tant qu'utilisateur je veux pouvoir identifier clairement et rapidement les périodes de tensions sur le réseaux 

Aujourd'hui on a uniquement 2 grosses bandes rouges, ça mériterait d'avoir soit un autre élément graphique pour les identifier soit du wording

**Comment by Clem-mrtn** [comment]
https://wattris.ademe.fr/
Suite aux échanges : rajouter la notion de _période_ au wording :  
- **Période de tension du réseau**
- **Période de tension**

**Comment by Clemog** [comment]
C'est bon :)

**Comment by florianpanchout** [comment]
Tout me parait bon. Je ferme l'issue
