### ISSUE TITLE
Sélectionner une durée <15 minutes

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#33]
> En tant qu'utilisateur je veux pouvoir renseigner mes usages au plus proche de ma "consommation"

Pour les petits appareils qui ont des gros pics à l'allumage comme la bouilloire, le sèche cheveux, micro-onde il faudrait pouvoir choisir une durée < 15minutes

**Comment by Clemog** [comment]
Possible de rester sur des pas de 30 minutes sur l'allumage mais diminuer la largeur du bloc

**Comment by Clemog** [comment]
A noter un temps long avant affichage si bcp de blocs générés (reproductible pour les appareils appelant une forte puissance sur une période de temps longue)
-> Nécessitera peut être un re-travail sur la conception des steps pour optimiser ce temps notamment si on diminue le pas de temps

**Comment by florianpanchout** [comment]
C'est visible ici : https://deploy-preview-60--wattris.netlify.app/

Aussi corrigés : 
- On affiche maintenant un seul bloc peu importe la puissance. 
- La durée des appels de puissance au démarrage de l'appareil sont maintenant liés à l'attribut `initialPowerLength`
- Le score affiche maintenant la bonne valeur

**Comment by Clem-mrtn** [comment]
Est-ce qu'on afficherait pas < 15minutes ou une fourchette 0-15min ? 
J'ai un peu peur qu'une durée en dure de 15 minutes peuvent bloquer encore les utilisateurs : "je fais bouillire de l'eau 2/3 minutes max blablabla"

**Comment by florianpanchout** [comment]
C'est visible ici : https://deploy-preview-67--wattris.netlify.app/

Je n'ai pas modifié les defaults des appareils. Je ne sais pas si c'est nécessaire

**Comment by Clem-mrtn** [comment]
ça me parait très bien ! 

> Je n'ai pas modifié les defaults des appareils

Comment ça ?

**Comment by Clemog** [comment]
> Comment ça ?

(Mettre la valeur par défaut de la bouilloire à 5 minutes plutôt que 30)

Je pense que c'est nécessaire, je peux modifier ça

**Comment by florianpanchout** [comment]
Ça devrait même être une réflexion plus large sur l'ensemble des valeurs par défaut non ? Sauf si tu l'as déjà fait à un moment (de mon côté j'ai plus ou moins mis des valeurs au pif au début)

**Comment by Clemog** [comment]
Pdt le design des appareils, j'avais reporté les durée moyennes de cycles et d'utilisation
