### ISSUE TITLE
Paramétrer l'iframe 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#34]
Pour intégration sur le site ecowatt du RTE & autres sites à venir 
https://wattris.netlify.app/integration

**Comment by Clem-mrtn** [comment]
Et + intégration dans l'application

**Comment by florianpanchout** [comment]
Est ce que l'on fait une page à part pour l'intégration ou est ce que ça doit être sur la home directement ? Genre placé en dessous du simulateur. Vu que le site wattris.ademe.fr est plus dédié aux réutilisateurs qu'au grand public

**Comment by Clemog** [comment]
Mais il ne faudrait pas que la section apparaissent sur l'iframe on est d'accord ?

**Comment by Clem-mrtn** [comment]
> ça doit être sur la home directement ? 

Genre le configurateur d'intégration directement sur la homepage d'ecowatt ?

**Comment by florianpanchout** [comment]
Non non. La home de wattris.ademe.fr aurait cette structure : 

<img width="595" alt="Screenshot 2022-12-12 at 12 29 53" src="https://user-images.githubusercontent.com/8115933/207034611-d3496de5-870f-4fcb-a0ed-ba779e579d13.png">


Et l'iframe ressemblerait toujours à ça : 

<img width="1020" alt="Screenshot 2022-12-12 at 12 30 25" src="https://user-images.githubusercontent.com/8115933/207034652-8927dbb4-dfb5-46e4-bec0-06e1b11d4d2a.png">

**Comment by Clem-mrtn** [comment]
Ah oui carrément sur la même page je trouve ça très bien ! 👍

**Comment by florianpanchout** [comment]
Nope, pas de paramètre pour l'instant. A terme, on pourrait imaginer choisir les appareils affichés par défaut
