### ISSUE TITLE
Ajouter un texte introductif au simulateur 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#35]
> En tant qu’utilisateur, avant de vouloir utiliser le simulateur, je veux pouvoir comprendre pourquoi il est important de limiter ma consommation électrique pendant les pics quotidien.

Challenger Florence sur les textes d'intro, juste au dessus du simulateur, comme on peut le voir sur : https://wattris.netlify.app/integration

**Comment by florianpanchout** [comment]
Traité via https://github.com/datagir/wattris/issues/63

**Comment by Clem-mrtn** [comment]
Remettre le titre au-dessus du graphique même avec l'intégration du tuto

**Comment by florianpanchout** [comment]
[C'est visible ici]([Ajouter un texte introductif au simulateur #35](https://github.com/datagir/wattris/issues/35))
