### ISSUE TITLE
Ajouter texte explicatif forme des appareils

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#39]
- [x] Rédiger des petits textes d'explications à intégrer dans la pop-in d'ajout d'un appareil pour expliquer la forme des appareils

**Comment by Clemog** [comment]
Done pour une V1 (à relire néanmoins !), à voir comment ils peuvent être intégrés :)

**Comment by Clem-mrtn** [comment]
Je trouve les textes très bien, clairs, juste quelques retours : 
- Pour cohérence, rajouter le terme lave vaisselle  "**L'appel de puissance est maximal au début du cycle du lave vaisselle pour chauffer l'eau, puis reste inférieur à 150 Watt environ sur le reste du cycle (2000 Watt)."** _(dans toutes les autres descriptions on recite l'appareil)_ 
- Enlever la répétition pour la TV : tu précises déjà l'hypothèse. Proposition :  **"L'appel de puissance est maximal tout au long de l'utilisation de ma télévision (120 Watt). La puissance appelée peut varier entre 60 et 200 Watt selon la taille de la TV."**

**Comment by Clem-mrtn** [comment]
Pour ce qui est de l'UI et de l'intégration de ces hypothèses sur le simulateur j'imaginais plusieurs options.

**Option 1** : on intègre un petit picto "question"/information dans la popin de l'appareil et au clique on ouvre une nouvelle modale d'information 


![Image](https://user-images.githubusercontent.com/76995768/207303946-03fabb9f-f31d-4c5d-b412-45401511ef4f.png)
![Image](https://user-images.githubusercontent.com/76995768/207303945-9f54e3ee-8c2e-45c8-a7ff-27336eaeaa14.png)


**Option 2 :** un peu comme sur impact CO2 on met juste un lien "hypertexte" dans la popin appareil, qui ouvre soit une modale soit déroule les hypothèses juste en dessous _(avec ajout d'un scroll du coup dans la popin)_


![Image](https://user-images.githubusercontent.com/76995768/207304302-33f9bbac-105c-4d74-a628-0085d26c9e35.png)
![Image](https://user-images.githubusercontent.com/76995768/207304301-f33c31d3-91b1-49b9-8248-204cf00090ef.png)


**Option 3** : Quand on clique sur un appareil directement sur le graphique au lieu d'ouvrir la popin des appareils on ouvre une modal avec les hypothèses. Le risque c'est qu'on veut éventuellement ajouter le drag & drop et du coup pas sure de la fluidité

**Comment by florianpanchout** [comment]
L'option 2 me semble être la meilleure. Par contre ça risque d'être compliqué à gérer visuellement. Si la modal devient trop grosse, on ne voit plus le graph derrière.

Peut être un mélange de l'option 1 et l'option 2 ? Au lieu d'ouvrir une nouvelle modal, on remplacerait le contenu de l'actuelle

**Comment by florianpanchout** [comment]
Lié à #24

**Comment by Clemog** [comment]
Yes, c'est ce qu'on se disait hier : l'option 1 qui n'ouvre pas une modal mais ajoute un texte dans la modal actuelle
