### ISSUE TITLE
Meta image / meta description 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#46]
Créer une méta image et une méta description du simulateur Wattris pour le partage de l'outil

**Comment by Clem-mrtn** [comment]
Je ne sais pas du tout quelle est la longueur d'une méta descrption 😅 
" **Découvrez Wattris, le jeu pour apprendre à consommer au bon moment et ainsi évitez les risques de coupures d'électricité en France cet hiver** "

**Comment by florianpanchout** [comment]
Entre 50 et 160 signes. Donc on est bon aha

Par contre la description est toujours accompagnée du titre, donc ça ne fait pas un peu doublon ?

Si on prends en compte le titre, ça pourrait donner quelque chose comme ça ? 

> ### Wattris, le jeu pour éviter les coupures cet hiver !
> Simulez la consommation électrique de votre foyer, découvrez quels appareils consomment beaucoup, et apprenez les bons gestes pour réduire la charge du réseau électrique

**Comment by Clem-mrtn** [comment]
Ça me va bien comme ça, je rajouterais bien d_'électricité_  


**Wattris, le jeu pour éviter les coupures d'électricité cet hiver !**

Simulez la consommation électrique de votre foyer, découvrez quels appareils consomment beaucoup, et apprenez les bons gestes pour réduire la charge du réseau électrique

**Comment by florianpanchout** [comment]
C'est en prod !

(J'ai aussi ajouté favicon / metaimage)

**Comment by Clemog** [comment]
(Je crois que j'ai pas le favicon dans mon navigateur ?)
