### ISSUE TITLE
Ajouter un appareil sur toute une journée 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#48]
Suite à la discussion sur l'issue #32 
> Oui, il y a un travail de design sur cet "affichage 24h" qui est bien un mode d'ajout spécifique. Et c'est également noté qu'il faut travailler, à priori, spécifiquement sur le parcours d'ajout du chauffage.

Quand je coche **"Allumage toute la journée"** je ne peux pas choisir sur la popin mon heure d'allumage notamment pour le chauffage où j'ai encore un pic de puissance à l'allumage (18h)
![image](https://user-images.githubusercontent.com/76995768/207305459-80839e64-b2ae-4df6-a142-505908476fe3.png)
Il semble aussi y avoir un bug sur la petite carte puisque celle-ci affiche "**Pendant 01h00"** 
![image](https://user-images.githubusercontent.com/76995768/207305599-d7ee493d-04ca-40fc-a784-e3dc09e89798.png)

De +  dans [les hypothèses](https://github.com/datagir/wattris/pull/43) on dit qu'on a fait le choix de ne pas prendre de pic de conso à l'allumage. 
=> que choisit-on donc de faire sur cet affichage ?

**Comment by Clemog** [comment]
Je pense que le travail est en cours du côté de Florian d'ou les quelques bugs

Pour le chauffage, comme on le disait, il est à traiter séparément (notamment en demandant les température consigne éventuellement qui ferait varier le temps initial à Pmax)  

c'est une imprécision dans la description, il faut bien prendre en compte le pic d'allumage ;)

**Comment by florianpanchout** [comment]
Pour l'instant, on n'affiche pas de pic d'allumage lorsque l'appareil est constamment allumé. Ça me semble être le choix le plus logique non ? Je ne vois pas comment faire autrement

Pour les cartes en bas c'est effectivement un bug

**Comment by Clemog** [comment]
A mon avis pour le chauffage, ça pose problème, l'appel de puissance est élevé si toute la journée à 20 degrés par exemple

Et pour certains appareils, je pense qu'on ne devrait pas afficher ce bouton

**Comment by florianpanchout** [comment]
Le chauffage est tellement particulier qu'il devrait être traité dans une issue à part je pense. Je propose qu'on l'oublie ici et que l'on essaie de trouver une solution qui convienne déjà à tous les autres appareils

> Et pour certains appareils, je pense qu'on ne devrait pas afficher ce bouton

Tu penses auxquels et pourquoi ?

**Comment by Clemog** [comment]
On a répondu ce matin mais l'argument était au niveau de la cohérence (on ne va jamais mettre un lave vaisselle toute la journée)

**Comment by florianpanchout** [comment]
C'est corrigé pour l'affichage incohérents des tuiles en bas. Elles commencent à être assez chargées, il faudra peut être trouver une façon de les simplifier
