### ISSUE TITLE
Nouvelle UI ajout radiateur électrique 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#56]
Travailler un nouvel affichage pour le chauffage et voir quelle forme on impute à l'appareil (pic de puissance ou pas) 
Valider nos hypothèses avec le métier

**Comment by Clemog** [comment]
Réfléxions ici : https://excalidraw.com/#room=ec5fb3052e72be743000,I4ir7MMgOr5fTRIwlGAy7A

**Comment by Clem-mrtn** [comment]
Retour métier qui confirme la démarche : 
>   Il faudrait affiner le profil de conso des radiateurs, avec notamment la température de consigne (dont on parle beaucoup) mais aussi des données permettant de chiffrer les besoins de chauffage (taille du logement ou des pièces chauffées notamment)

**Comment by Clemog** [comment]
Pour moi, retour métier qui va à l'encontre de nos réflexions. 
1) Nous ne disposons pas de la donnée pour quantifier précisément la puissance appelée selon ces différents facteurs.
2) Les personnes ne connaissent pas forcément les informations techniques de leur chauffage
3) La température consigne est loin d'être connue, peu de personnes possèdent un thermostat à priori

**Comment by Clem-mrtn** [comment]
Suite au point du 02/01, pour une première version d'ajout du chauffage : 
- Modifier le wording *Je lance* par *Je chauffe* (le pic de conso afficher à l'heure à laquelle on pousse le radiateur) 
- Pouvoir sélectionner un mode nuit / veille pour l'ensemble de ses chauffages (i.e : les appareils sont allumés en permanence) 

Dans une V2 du chauffage réfléchir avec le métier comment intégrer la T° dans le paramétrage de son appareil 
voir 1er travail de @Clemog : https://excalidraw.com/#room=ec5fb3052e72be743000,I4ir7MMgOr5fTRIwlGAy7A

**Comment by Clemog** [comment]
Mieux vaut regarder le [figma](https://www.figma.com/file/cJYrwRiAvp1DJ6ZAbAkX1K/Wattris?node-id=53%3A2&t=pzaKDInjrAIQ8JQ4-0), l'excalidraw était très tourné UX :)

**Comment by florianpanchout** [comment]
> Modifier le wording Je lance par Je chauffe (le pic de conso affiché à l'heure à laquelle on pousse le radiateur)
Pouvoir sélectionner un mode nuit / veille pour l'ensemble de ses chauffages (i.e : les appareils sont allumés en permanence)

Pourquoi c'est dans reviewed alors que ces 2 points ne sont pas traités ?

**Comment by Clem-mrtn** [comment]
Hum il me semble parce que tu as fermé l'issue mercredi ou jeudi et qu'on a créé une nouvelle issue #85 sur le sujet donc j'en ai déduis qu'on traiterait ces 2 points dans le dvpt de cette issue
Mais je ne les avais pas linké, du coup je repartage ces 2 points dans l'issue #85
