### ISSUE TITLE
🐛 Bug avec le variable Peak

### ISSUE THREAD

**Issue by Clemog** [datagir/wattris#58]
Je note un bug avec la variable `peak` n'affiche l'appareil en rouge seulement si le début de l'utilisation est dans un pic

<img width="989" alt="image" src="https://user-images.githubusercontent.com/55186402/207609837-f6ae4bbf-c33b-4a35-b7f0-9d3f7e5be8bd.png">

J'ai réfléchis à plusieurs options :
- Changer la définition de cette variable en utilisant également la durée d'utilisation pour évalur `peak`. Mais dans ce cas, n'afficher en rouge que les appareils qui appellent une forte puissance
- Définir peaak dans Dataprovider ?

**Comment by florianpanchout** [comment]
J'ai modifié l'indicateur. La tuile s'affiche maintenant en rouge si : 

- L'appareil a un pic d'allumage et une partie de ce pic est pendant les périodes de tension
- L'appareil n'a pas de pic d'allumage, n'est pas allumé toute la journée, sa puissance appelée et supérieure à 20W et il est appelé pendant les pics de tension

C'est visible ici : https://deploy-preview-77--wattris.netlify.app/

**Comment by Clemog** [comment]
Top ! A mon avis il faut que cette hypothèse soit visible quelque part sur le site
