### ISSUE TITLE
Choix du nom

### ISSUE THREAD

**Issue by florianpanchout** [datagir/wattris#6]
En fonction du [périmètre du simulateur](https://github.com/datagir/simulateurpuissance/issues/5) : 

- [x] trouver un nom pour le simulateur
- [ ] choisir une url associée (et son format : ".gouv.fr" ? ".ademe.fr", ".fr" ?)

**Comment by Clemog** [comment]
Yes très bien !

**Comment by florianpanchout** [comment]
Adjugé vendu. J'ai renommé les outils en fonction.

Je remets dans backlog en attendant le choix du ndd

**Comment by florianpanchout** [comment]
Est ce que l'on réserve wattris.ademe.fr ? Ça ne coute rien de mettre cette version du simulateur en ligne non ?

**Comment by florianpanchout** [comment]
Demande de création de sous domaine faite à l'instant (via le formulaire interne ADEME)

**Comment by florianpanchout** [comment]
Le site est en ligne : https://wattris.ademe.fr/
