### ISSUE TITLE
Gérer la hauteur maximum des blocs sur le graphique 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#66]

**Comment by florianpanchout** [comment]
C'est compliqué de savoir comment représenter graphiquement le dépassement tant que l'on a pas la réponse à la question posée au métier. 

Pour rappel : 

> Est ce que la puissance appelée à un instant T a une importance au niveau du réseau ou c'est la consommation pendant les pics de tension qu'il faut prendre en compte. 

Parce que si ces blocs sont "ultra" problématiques, il faut trouver un affichage pour vraiment les mettre en avant. Alors que s'ils sont "justes" aussi problématiques que les autres rouges, un affichage simple fait l'affaire

**Comment by florianpanchout** [comment]
Pour l'instant j'ai juste mis un gradient, en attendant une réponse du métier. 

[C'est visible ici](https://deploy-preview-82--wattris.netlify.app/)

**Comment by Clem-mrtn** [comment]
> Pour l'instant j'ai juste mis un gradient

Par gradient, tu entends l'effet dégradé sur le haut des barres ?

**Comment by florianpanchout** [comment]
Yes
