### ISSUE TITLE
Afficher moins d'informations sur les cartes appareils

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#69]
Alléger l'affichage des cartes appareils sous le graphique qui sont assez chargées 
- Ne faire apparaître que le slider pour modifier l'utilisation des appareils dans le temps 
- Peut-être laisser la possibilité de cocher "*Allumé toute la journée*" et de jouer avec la représentation

**Comment by Clemog** [comment]
Une nouvelle issue a été ouverte suite aux modifs liées au design du chauffage pour les cartes du bas ? (même sujet que cette issue)
