### ISSUE TITLE
Modifier le texte du score consommation faible 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#70]
J'ai découpé l'issue #61 pour qu'on modifie le wording directement avant de réfléchir à l'amélioration des différents seuil d'affichage 
Lorsque la consommation est faible modifier "*Votre consommation est raisonnable et ne met pas le réseau en tension.*"  par **"Votre consommation est modérée durant les périodes de tension du système électrique"**

**Comment by florianpanchout** [comment]
Done. [C'est visible ici](https://deploy-preview-80--wattris.netlify.app)

J'en ai profité pour corriger l'erreur de conversion Wh kWh (ça n'a visiblement choqué personne que l'on arrive facilement à 5000 kWh par jour...)
