### ISSUE TITLE
Afficher les valeurs par défaut de chaque appareil

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#73]
Mettre les valeurs d'utilisation par défaut pour chaque appareil : _ex Bouilloire 5 min_

**Comment by Clem-mrtn** [comment]
Cette issue est dans _done_ mais je ne vois pas la MAJ sur la dernière version de Wattris ou sur une branche de démo ? (dans la PR 79)

**Comment by Clemog** [comment]
Yes pour moi il fallait une review rapide de Florian mais ça me semble ok de merger

**Comment by florianpanchout** [comment]
C'est merged
