### ISSUE TITLE
Ajouter un encart "nous contacter" pour tests utilisateur

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#76]
Afin de pouvoir échanger avec des utilisateurs et récolter leur retour sur l'outil, faire apparaître par exemple à la fin de la simulation  une popin qui leur demande de nous laisser leur _mail + un retour écrit_ si ils le souhaitent pour les recontacter derrière

OU alors intégrer un petit encart sous le graph 

=> plugguer sur Airtable ?

**Comment by Clem-mrtn** [comment]
Retour intéressant de Jérémy qui conseillait d'ajouter 2 ou 3 questions en amont de demander le mail pour les recontacter. 
+ conseiller de passer par un petit formulaire Airtable

**Comment by Clem-mrtn** [comment]
J'ai créé un Airtable et un formulaire par la même occasion avec 3/4 questions et la possibilité de laisser son email 
https://airtable.com/appHoKDgtUNI8q77p/tblLuHjGv1R2xgsgT/viw0lGZoOqJY7rMfF?blocks=hide

A voir du coup si on met simplement un lien vers le formulaire ou si on développe une popin comme échangé hier ou on propose également la possibilité de partage sa simulation

**Comment by Clem-mrtn** [comment]
=> Partir sur le développement d'une popin "native" où on aurait le formulaire de feedback + du coup la possibilité de partager sa simulation (connecté  via l'API airtable) 
Link #75

**Comment by florianpanchout** [comment]
Visible ici : https://deploy-preview-105--wattris.netlify.app/

On enregistre la simulation dans un champ caché.

Je ne suis pas convaincu par les questions posées : j'ai l'impression que je ne saurais pas comment les différencier. Est ce que NPS + facilité d'utilisation ne suffirait pas ?

**Comment by Clemog** [comment]
Je trouve le CTA un peu trop voyant par rapport aux appareils mais pas vraiment important 😂
<img width="975" alt="image" src="https://user-images.githubusercontent.com/55186402/212053266-c668c6ec-2dda-472e-951f-4b35293a2b46.png">

**Comment by florianpanchout** [comment]
> Ok donc de facto, la simulation est enregistrée dans le airtable en même temps que les retours ? Est-ce qu'on a pas besoin niveau RGPD d'être transparent là dessus ? Dans les cookies ?

Bonne question. On pourrait conditionner l'envoi à une checkbox, mais je ne vois pas d'affichage conditionnel sur le form airtable. De la même façon, je ne vois pas comment afficher un disclaimer en bas du form. J'imagine que ça fait parti des options payantes

**Comment by Clemog** [comment]
Sinon, on peut rajouter une question "obligatoire", ou on doit répondre 'oui' comme disclaimer ?
Genre "j'autorise Datagir à collecter ....."

**Comment by florianpanchout** [comment]
Prévenir l'utilisateur après l'envoi me semble être un bon gros dark pattern. 

La checkbox me semble être la meilleurs solution avec nos moyens.

**Comment by florianpanchout** [comment]
J'ai trouvé l'affichage conditionnel (qui était pourtant assez visible...). On a maintenant une checkbox "J'accepte de partager ma simulation en cours avec Datagir" qui conditionne l'envoi de la simulation. On peut valider le formulaire sans cocher cette case

**Comment by florianpanchout** [comment]
Je reproduit ici les retours de @supersuperflux ici : 

**Objectif des questions**

- Je n’ai pas compris ce que vous cherchiez à faire avec cette modale de satisfaction : que vont vous apporter ces données ? Ce sont à mon sens des “métriques de vanité” : on est contents que les gens recommandent le site, mais on veut plutôt savoir POURQUOI ils le recommandent que S’ILS le recommandent.
Si vous voulez améliorer cette partie et capter des retours qualitatifs, on pourrait avoir une question conditionnelle lorsque la personne entre une donnée en-dessous de 6 → champ libre (texte) pour donner son avis (pas obligatoire bien sûr).
- L’échelle de 1 à 10 sur la difficulté ne me semble pas efficace, idéalement il faudrait s’orienter :
- soit sur une échelle neutre (boutons radio allant de “difficile” à “facile” avec seulement 5 choix) car les étoiles apportent ici de la confusion dans la compréhension ;
- soit laisser l’usager choisir un terme entre : “facile”, “moyennement facile”, “difficile”, “très difficile” par exemple.
Pareillement, ici, si la personne répond “difficile” ou “très difficile”, on peut avoir envie de creuser.
- Nickel pour le texte du champ d’email ! J’aurais peut-être renforcé le discours en tournant les choses de cette façon :

*Merci pour votre précieux retour ! Vous souhaitez contribuer à enrichir le simulateur ? Renseignez votre email pour rejoindre notre groupe de bêta-testeurs. 👇*

[Remerciement] [Explication de la promesse : pourquoi ils s’engageraient ?] [Explication ce à quoi va servir leur adresse email]

## Questions/idées

- Déjà, identifier ce que vous voulez mesurer comme retours → grande tendance/satisfaction globale ? des retours plus précis ? des points d’amélioration concrets ?
- Où va la donnée ? → est-ce pour nourrir votre page Statistiques ? dans le but de répondre à une commande/subvention ? est-ce pour donner une orientation au produit ?
- Peut-être que dans un premier temps vous pourriez vous concentrer sur un seul aspect ? (Facilité/Difficulté ou Satisfaction) selon ce qui vous importe le plus. Les usagers seront plus enclins à remplir un formulaire court et impactant, plutôt qu’un formulaire long.
- Le “je donne mon avis” laisse entendre que l’usager va avoir un champ libre à un moment, or pour l’instant on a des questions fermées → si vous souhaitez avec des retours qualitatifs, vous pourriez avoir un champ libre lorsque la personne émet un avis neutre voire négatif, ça lui laissera l’opportunité de s’exprimer.
- Peut-être couper l’expérience en deux : temps 1 : j’ai accès à des étoiles dans l’interface Wattris directement et lorsque je clique, on me demande mon avis et mon email ?
- Pour inspiration : chez mon-entreprise, j’ai eu l’occasion de bosser sur ce sujet car on arrivait pas à avoir de retours des gens (le module de satisfaction était tout en bas, bien en dessous de la ligne de flottaison). J’ai proposé un parcours en plusieurs temps, avec un module de satisfaction en libre accès constant. Illustration :

**Comment by Clem-mrtn** [comment]
Top, merci pour tous ces retours ! 
@supersuperflux si tu es dispo, on peut peut-être s'en parler mardi après-midi au sprint planning ? 
Afin de voir comment on peut simplement améliorer l'enquête

**Comment by supersuperflux** [comment]
Yes @Clem-mrtn, tu m'envoies une petite invit' que je vous rejoigne ? :)

**Comment by Clemog** [comment]
Sujets potentiellement bloquant :

- Modal d'ajout d'un appareil
- Composition des ses équipements facile
- Score
- Puissance vs consommation
- Pourquoi les pics 
- Visualisation des appareils

**Comment by florianpanchout** [comment]
> Je ne comprends pas s'il est question de puissance ou bien consommation des appareils

Audacieux ça non ? 

Le reste me semble pas mal du tout !

**Comment by supersuperflux** [comment]
Ça fonctionne bien ! À mon sens, vous pouvez proposer plusieurs réponses. 
Voici mes propositions d’ajustement des formulations **en gras**.  

**Qu’est-ce qui n’a pas fonctionné pour vous (plusieurs réponses possibles) ?**

- Je n'ai pas réussi à ajouter un appareil facilement
- Je n'ai pas réussi à composer **mon set d’équipements** facilement 
- Je ne parviens pas à visualiser chacun de mes appareils sur le graphe
- Je ne comprends pas la forme des blocs des appareils **? -> pas compris cette proposition**
- Je **ne comprends pas** le principe du score
- Je ne comprends pas pourquoi certaines périodes de la journée sont **rouges (heures de tension du réseau)**
- Je ne comprends pas le graphe. **-> pour avoir une proposition plus neutre sur le sujet de la puissance vs. consommation.**

**Comment by Clem-mrtn** [comment]
Ca me paraît bien ! 
Juste, je ne comprends pas trop  la question ? 
> Je n'ai pas réussi à composer mes équipements facilement

Et je reformulerai cette question : *Je ne comprends pas le principe du score* par 
**Je ne comprends pas mon score consommation** 
(la notion de principe est un peu vague et on formule jamais trop qu'il s'agit d'un score sur le graphique)

On a 7 propositions est-ce que ce n'est pas trop ?
Est-ce que les réponses à choix multiples ça ne complexifie pas le traitement des réponses ?

**Comment by Clemog** [comment]
> Audacieux ça non ?

Yes et je pense que c'est pas nécessaire dans le sens ou je sais pas ce qu'on pourrait tirer de cette info

> * Je ne comprends pas la forme des blocs des appareils **? -> pas compris cette proposition**

Certains appareils ont une forme de rectangle, d'autres en L sur le graphe, à priori c'est pas évident à expliquer au premier abord si on ne lit pas la bulle info sur la modal d'ajout d'un équipement

> Je n'ai pas réussi à composer mes équipements facilement

Le "set" d'équipement est peut etre plus parlant. Je me dis que certaines personnes vont peut etre bloquer sur "flemme de rentrer autant d'appareil car trop long"
Peut etre que la phrase pourrait être : "Ajouter chacun des appareils de mon logement est trop long"

> Et je reformulerai cette question : _Je ne comprends pas le principe du score_ par

Yes pourquoi pas !

> On a 7 propositions est-ce que ce n'est pas trop ?

Je pense aussi, j'avais volontairement posé plusieurs questions pour avoir un peu de choix

**Comment by Clemog** [comment]
Et je me pose une autre question sur la formulation "je ne comprends pas", je me dis que ça "incrimine" fortement les capacités de l'utilisateur à comprendre alors que c'est peut-être un mauvais design de notre côté

**Comment by supersuperflux** [comment]
> Et je me pose une autre question sur la formulation "je ne comprends pas", je me dis que ça "incrimine" fortement les capacités de l'utilisateur à comprendre alors que c'est peut-être un mauvais design de notre côté

Oui, clairement ça angle les choses de manière plutôt négative.

En reprenant tous les échanges, je me dis qu'on peut dégager de grandes tendances en posant la questions sur un format plus neutre, type :

Que souhaiteriez-vous améliorer dans ce simulateur (plusieurs réponses possibles) ?
- L’ajout d’un appareil
- L’ajout d’un groupe d’appareils
- La visualisation des appareils sur le graphe
- La compréhension du graphe
- Le score de consommation
- La compréhension des périodes rouges (heures de tension du réseau).

Qu'en dites-vous ?

**Comment by Clem-mrtn** [comment]
Je me dis que la question _Je ne comprends pas pourquoi certaines périodes de la journée sont rouges (heures de tension du réseau)_ est + liée au contenu explicatif autour du simulateur (toute la pédagogie autour des périodes de tension) qu'aux fonctionnalité de l'outil donc moins pertinent pour nous ? 
Surtout s'il y a du contenu en amont de l'iframe pour l'expliquer 

Et on peut peut-être fusionner les questions : _je ne comprends pas la forme des blocs des appareils ?_  et la remplacer simplement par **"Je ne comprends pas le graphique et la forme des appareils"** ?

Ca donnerait : 
Qu’est-ce qui n’a pas fonctionné pour vous (plusieurs réponses possibles) ?

- [ ]     L'ajout d'un ou plusieurs appareils est difficile
- [ ]     La visualisation de chacun de mes appareils sur le graphe n'est pas clair
- [ ]     Le score consommation n'est pas compréhensible
- [ ]     Le graphe et la forme des appareils ne sont pas clairs

**Comment by Clemog** [comment]
Carrément d'accord avec les 4 options !

Au niveau du wording de la question, j'ai peur que "fonctionné" soit plus compris comme "ça ne fonctionne pas du tout" plutôt que "c'est pas bien fait"

j'ai bien le côté positif de l'amélioration

**Comment by Clem-mrtn** [comment]
Haha quelle synchronisation 
> Qu'en dites-vous ?

Ça me va très bien !
Par contre j'ai l'impression qu'on ne peut pas mettre de smiley dans les formulaires Airtable (version gratuite)
Possible de paramétrer cette question en dev ?

**Comment by florianpanchout** [comment]
Est-ce qu'on est sur que "graphe" est un terme bien compris ? Je ne me rends pas compte

> Possible de paramétrer cette question en dev ?

Tu veux dire redévelopper le form ? C'est possible mais peu cohérent avec notre volonté de ne plus passer de temps sur le produit

**Comment by supersuperflux** [comment]
> Par contre j'ai l'impression qu'on ne peut pas mettre de smiley dans les formulaires Airtable (version gratuite)

Pour faire écho à la remarque de Florian, peut-être que des étoiles suffisent (5 de préférence) ? Au niveau 3 (moyen, neutre), on peut demander un avis.

> Est-ce qu'on est sur que "graphe" est un terme bien compris ? Je ne me rends pas compte
Je pense que c'est un terme assez générique pour être connu, mais on peut opter pour "représentation graphique" si ça vous semble plus évocateur.

**Comment by florianpanchout** [comment]
J'ai fait un essai pour pouvoir comparer la présentation smileys et étoiles : https://deploy-preview-105--wattris.netlify.app/

**Comment by Clem-mrtn** [comment]
Je trouve que les smileys sont trop petits, on arrive pas bien à différencier le _neutre_ du *pas content*
Soit on part sur des smileys très différenciés mais je trouve que ça reste petit, soit sur une échelle avec des étoiles qui je pense permet plus une _palette d'émotions_ (que c'est beau) pour l'utilisateur 

J'ai mis à jour le form pour voir ce que ça donnerait, j'ai passé la question des améliorations au conditionnel : https://airtable.com/shrp4omaHLOXGZ2mu

**Comment by florianpanchout** [comment]
Les étoiles rendent mieux je trouve oui

**Comment by supersuperflux** [comment]
Ça me semble très cool tout ça !

**Comment by florianpanchout** [comment]
J'ai juste une question sur la formulation "Qu'est ce qui n'a pas fonctionné pour vous" => dans la tête des gens il y a une différence entre quelque chose qui fonctionne et quelque chose qui est mal fait non ?

**Comment by Clem-mrtn** [comment]
Yes, j'ai repris la tournure de Laura pour qu'on soit plus dans le côté améliorations : https://airtable.com/shrp4omaHLOXGZ2mu

**Comment by florianpanchout** [comment]
Il semble y avoir consensus, je merge
