### ISSUE TITLE
🐛 Bug checkbox "allumé toute la journée" si plusieurs appareils identiques

### ISSUE THREAD

**Issue by Clemog** [datagir/wattris#78]
J'ai noté un bug dans le cas ou on a plusieurs appareils identiques (2 lave linges) : le click sur la checkbox déclenche l'action sur le premier appareil

**Comment by Clemog** [comment]
@florianpanchout j'avoue que je ne trouve pas d'ou vient ce bug, incompréhensible de comprendre pourquoi l'index passé à la checkbox est différent de celui passé aux autres composantes

**Comment by florianpanchout** [comment]
Issue obsolète via #56 non ?
