### ISSUE TITLE
Mettre en évidence la période d'utilisation

### ISSUE THREAD

**Issue by florianpanchout** [datagir/wattris#84]
Pour les appareils type radiateurs/ampoules il faudrait mettre en évidence la période d'utilisation (entre les deux thumbs). Jouer avec l'opacité (100% pour la période selectionnée, moins pour le reste de la journée) semble être la meilleure solution

**Comment by Clem-mrtn** [comment]
#83

**Comment by florianpanchout** [comment]
Done : https://deploy-preview-104--wattris.netlify.app/

**Comment by Clem-mrtn** [comment]
Pas sûre de bien voir ce qui a changé dans cette nouvelle branche ? 
Quand je sélectionne Radiateur ou ampoule aujourd'hui, visuellement j'ai une opacité à 100% sur toute leur période d'utilisation ?
