### ISSUE TITLE
Modifier l'UI pour l'ajout/ suppression d'un deuxième appareil 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#85]
Suite aux échanges sur Mattermost 
> les bouton +/- en dessous ne sont pas clairs. On ne comprend pas que c'est pour ajouter un nouvel appareil, le positionnement des boutons collés aux barres rend ça moins lisible aussi je trouve. Ca manque d'un wording peut-être : " Ajouter un deuxième appareil"

**Comment by Clemog** [comment]
Une autre idée : utiliser un système de '"numéros" pour faire comprendre qu'on a l'appareil numéro 1, puis qu'on peut ajouter "un numéro 2"

**Comment by florianpanchout** [comment]
Le problème c'est de trouver le bon wording. On ajoute pas forcement un deuxième appareil, mais peut être une deuxième utilisation de l'appareil.

Dans le code on sépare les "occurences" des "appliances". Je peine à trouver un terme français compréhensible pour représenter l'action du CTA.

En attendant mieux j'ai mis "Ajouter un appareil". C'est visible ici : https://deploy-preview-103--wattris.netlify.app/

**Comment by Clem-mrtn** [comment]
Beaucoup + clair, dans l'utilisation 👍 
> On ajoute pas forcement un deuxième appareil, mais peut être une deuxième utilisation de l'appareil.

Oui je vois ce que tu veux dire sauf que ça dépend du cas d'usage : par exemple pour le radiateur électrique moi j'en ai 4 chez moi, donc dans le cas de ma simulation j rajoute vraiment un 2ème appareil et non pas vraiment un 2ème usage du même appareil 

> utiliser un système de '"numéros" pour faire comprendre qu'on a l'appareil numéro 1, puis qu'on peut ajouter "un numéro 2"
Je suis d'accord, si on assume le "terme" appareil (*Ajouter un appareil*) les numéroter pour que ce soit plus simple à suivre sur le graphique (radiateur éléctrique 1, radiateur électrique 2 etc.)

**Comment by florianpanchout** [comment]
C'est fait : https://deploy-preview-103--wattris.netlify.app/
