### ISSUE TITLE
Modifier l'affichage des cartes en bas du graphique 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#86]
Suite aux discussion Mattermost 
> Les cartes sont trop simplifiées. On ne sait pas que l'on peut cliquer dessus pour ajouter un appareil (ou même modifier l'appareil)

- Afficher quelques informations pour faciliter la compréhension des cartes 
- Rendre cliquable la carte dans son intégralité ?

**Comment by florianpanchout** [comment]
J'ai ajouté un picto : https://deploy-preview-93--wattris.netlify.app/
