### ISSUE TITLE
Retourner à la liste des appareils en cliquant sur la croix de la popin

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#87]
> Avec cette nouvelle interface de liste des appareils, je trouve ça dommage que lorsque l'on est sur le paramétrage d'un appareil et que l'on clique sur la croix, on ne puisse pas revenir à la liste de tous les appareils plutôt que de fermer la popin

**Comment by florianpanchout** [comment]
Done : https://deploy-preview-89--wattris.netlify.app/
