### ISSUE TITLE
Rajouter un appareil existant

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#88]
Je me permets de remettre mon commentaire dans cette issue 
>dans l'UX, une fois que l'on a ajouté un radiateur par exemple, on ne peut plus le sélectionner en Ajoutant un nouvel appareil. Or, si un utilisateur passe à côté de l'ajout d'un 2ème appareil et souhaite le réajouter il ne peut pas, il est obligé de recliquer sur la carte pour la modifier

Est-ce qu'on veut ne plus rendre cliquable l'ajout d'un 2ème radiateur par chemin utilisateur "principale" ? (_Ajouter un appareil > Radiateur électrique  > Paramétrer son usage)_
Cela ne risque t-il pas d'être bloquant ?

**Comment by Clem-mrtn** [comment]
Afficher en mode bouton secondaire mais permettre le clique

**Comment by florianpanchout** [comment]
Done : https://deploy-preview-89--wattris.netlify.app/
