### ISSUE TITLE
Remplacer le lien "Découvrez des éco-gestes" par lien du site Agir

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#94]
Retour de Florence :
> Mettre un bouton « Plus de solutions pour faire des économies d’énergie » en fin de jeu
Et renvoyer vers https://agirpourlatransition.ademe.fr/particuliers/maison/economies-denergie

Je reposte son retour mais j'ai un peu de mal à voir comment l'intégrer au simulateur. On a pas vraiment de "fin de jeu"... 
**=> on peut p-t essayer de l'intégrer dans l'encart Partager sa simulation / nous contacter : " Pour aller + loin :" 
OU alors faire apparaître automatiquement une popin au bout de 4/5 minutes de simulation** ?

**Comment by Clem-mrtn** [comment]
Remplacer le CTA "Découvrez des éco-gestes" par le CTA **" Découvrez comment faire des économies d'énergie toute l'année"** en redirigeant vers le site Agir : https://agirpourlatransition.ademe.fr/particuliers/maison/economies-denergie

**Comment by florianpanchout** [comment]
J'ai mis "Découvrez comment faire des économies d'énergie" pour que ça ne pête pas toute la mise en page (ça déborde sur "Période de tension" sinon)

[Visible ici](https://deploy-preview-101--wattris.netlify.app)
