### ISSUE TITLE
Ajouter les plages horaires dans le texte d'introduction du simulateur

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/wattris#99]
Remarque pertinente de Martin : 
Au delà des périodes horaires qu'on affiche dans le tuto, cela pourrait être bien de les avoir en dur dans le petit texte d'introduction. 
Par ex : **Simulez la consommation électrique de votre foyer, découvrez quels appareils consomment beaucoup, et apprenez les bons gestes pour réduire la charge du réseau électrique lors des périodes de tension de 8h à 13h et de 18h à 20h.**

**Comment by florianpanchout** [comment]
Done : https://deploy-preview-102--wattris.netlify.app/

**Comment by florianpanchout** [comment]
Done
